$axure.loadCurrentPage({
  "url":"商城vip.html",
  "generationDate":new Date(1385387515937.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"38e0cf48fc0e4b94a0522a1cdae7d175",
    "type":"Axure:Page",
    "name":"商城VIP",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62d689f64959437e90c4b8557fdcc1dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":1010,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c528cb1252ff4b549b77d295ca882aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":1010,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u0.png"}},
{
          "id":"47fc86ae2cb748bf9adda480f6ff5f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":151},
            "size":{
              "width":810,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43684dd4c61e4bf69bed667bee337af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":151},
                "size":{
                  "width":810,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u2.png"}},
{
          "id":"7fefc95cafc241e3bb6b82f585063b90",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":160},
            "size":{
              "width":10,
              "height":16}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商城vip/u4_line.png"}},
{
          "id":"0f0fa54d700e4877a75475a9c6aeb1d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":164},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b288535243034a8581d4a0c92754af32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":163,
                  "y":164},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35fe3e8e8cf04b00b12dfdef537d7c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a72467b5c4f4f4b8361e583e10c6ef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":215,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城道具",
                      "target":{
                        "targetType":"page",
                        "url":"商城道具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c3c8464369b497a990a16ba7bf2c9a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":230},
            "size":{
              "width":297,
              "height":350},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a616046f8a44f739071991f30a2c535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":163,
                  "y":230},
                "size":{
                  "width":297,
                  "height":350},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u9.png"}},
{
          "id":"92d5c3cdde454aa6b81898c659ee77db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":230},
            "size":{
              "width":320,
              "height":350},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efe4ebeaf0e4d5a92479f98a21f4c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":230},
                "size":{
                  "width":320,
                  "height":350},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u11.png"}},
{
          "id":"3457b57555974ea2abcec2327b93d1c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":220},
            "size":{
              "width":330,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商城vip/u13_line.png"}},
{
          "id":"befc642d1664430097594f74e824897f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":220},
            "size":{
              "width":360,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商城vip/u14_line.png"}},
{
          "id":"202163f16e77433ca2f5b5d1ae6177f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":204},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a8855683d4f4020a44b9e038e97955b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":204},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dea378d08a145b9838a65c6680e0555",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":204},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74746273cc154ca5b4b5b2084072d64f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":204},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cca710c1bfc349268bd37885f231cf52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":263},
            "size":{
              "width":45,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04eca12013094845a1a7399bc7894faf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":263},
                "size":{
                  "width":45,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0159fa6c60f04cc4ab102d7f82705ab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":237},
            "size":{
              "width":45,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d60e743b0f40c58d0c8eeaf9f0f4fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":237},
                "size":{
                  "width":45,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e658f39e853444082b4c73ea4265053",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":471},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9969958ac84e403a8b10158ee6ecdb80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":471},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5017a41ae969423db9bec44d0e65959d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":471},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1199960f3d47638c3845d0c570d2a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":471},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4e02e89f1da64fb1b2776d4f939c69de",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":502},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fba01fa18754fa88637719f81045edd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":502},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ff325ad1d5134379a96f63c6bdb76f2c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":502},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f00f6899e17947dc8252c7cb16e8b1b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":502},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c4c6e00d9957415bb17f446e4eaaa8e0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":528},
            "size":{
              "width":123,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bc65272e48ad476282c653a2db7f5466",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":471},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3fe7386fe6749ec83af65122ab62f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":471},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fd811ed6ad274b1eb38ee7acb20446a7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":471},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"010c9e89bb0f40fda0c5b30ecad76603",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":471},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bf60aa0a72ff438ba33c885fa95ae95e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":502},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8c4dcf499445b2b88c15c1de946442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":502},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6a6a0d1e73e34804a389661d3f1d2570",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":502},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acdd8752d35944a7ad3ed728840c5c20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":502},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"532cffd182c8435a91a083811d6aab91",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":528},
            "size":{
              "width":123,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e1ebac77bef47df829699c2d3e606ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":38},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc493e7e6f84146a0197a2bc89117fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":38},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14d254e2d4a54cdf9d2724857235cfac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":891,
              "y":38},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d1552fd5339490e8f900c212cc0fa62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":891,
                  "y":38},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69bde93244eb49e68809f3defbaffe57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1013,
              "y":38},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4e9970adb04cacac8e94192d5d13b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1013,
                  "y":38},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d55f4f542c7463380a6bfc4bebad5ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":40,
              "y":54},
            "size":{
              "width":1010,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b331705568df437394b70276a33283d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":40,
                  "y":54},
                "size":{
                  "width":1010,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u47.png"}},
{
          "id":"da6caa73d0924f9d9dbf1ccf698e2ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":337,
              "y":66},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b09742a94f84638b38d45d3251d8920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":337,
                  "y":66},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-成功登录",
                      "target":{
                        "targetType":"page",
                        "url":"主页-成功登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5309180970aa488bb5eec91a307b8666",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":66},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf5d336229046439535c57e2471befb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":66},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56d298ebd063453996f49c65457df482",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":66},
            "size":{
              "width":10,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页-直播大厅/u19_line.png"}},
{
          "id":"65e0f5a3242c44f28ac85cf95da89a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0x56F2F2F2},
            "location":{
              "x":140,
              "y":66},
            "size":{
              "width":170,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd6ac5cef5940bb84f7a988fd64db62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0x56F2F2F2},
                "location":{
                  "x":140,
                  "y":66},
                "size":{
                  "width":170,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u20.png"}},
{
          "id":"83e345c7bfe745fbb0ec54e3f0749e28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":194},
            "size":{
              "width":294,
              "height":109}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04643dafde84d84857abb21fa183971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":205,
                  "y":194},
                "size":{
                  "width":294,
                  "height":109}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u283.png"}},
{
          "id":"e9210e332e58426b98ac02534eac5c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":160},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03e795df9ade4117a7ac7cffaf3ac8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":447,
                  "y":160},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "62d689f64959437e90c4b8557fdcc1dc":{
      "scriptId":"u0"},
    "c528cb1252ff4b549b77d295ca882aaf":{
      "scriptId":"u1"},
    "47fc86ae2cb748bf9adda480f6ff5f48":{
      "scriptId":"u2"},
    "43684dd4c61e4bf69bed667bee337af1":{
      "scriptId":"u3"},
    "7fefc95cafc241e3bb6b82f585063b90":{
      "scriptId":"u4"},
    "0f0fa54d700e4877a75475a9c6aeb1d2":{
      "scriptId":"u5"},
    "b288535243034a8581d4a0c92754af32":{
      "scriptId":"u6"},
    "35fe3e8e8cf04b00b12dfdef537d7c91":{
      "scriptId":"u7"},
    "6a72467b5c4f4f4b8361e583e10c6ef1":{
      "scriptId":"u8"},
    "3c3c8464369b497a990a16ba7bf2c9a2":{
      "scriptId":"u9"},
    "0a616046f8a44f739071991f30a2c535":{
      "scriptId":"u10"},
    "92d5c3cdde454aa6b81898c659ee77db":{
      "scriptId":"u11"},
    "9efe4ebeaf0e4d5a92479f98a21f4c96":{
      "scriptId":"u12"},
    "3457b57555974ea2abcec2327b93d1c4":{
      "scriptId":"u13"},
    "befc642d1664430097594f74e824897f":{
      "scriptId":"u14"},
    "202163f16e77433ca2f5b5d1ae6177f9":{
      "scriptId":"u15"},
    "4a8855683d4f4020a44b9e038e97955b":{
      "scriptId":"u16"},
    "0dea378d08a145b9838a65c6680e0555":{
      "scriptId":"u17"},
    "74746273cc154ca5b4b5b2084072d64f":{
      "scriptId":"u18"},
    "cca710c1bfc349268bd37885f231cf52":{
      "scriptId":"u19"},
    "04eca12013094845a1a7399bc7894faf":{
      "scriptId":"u20"},
    "0159fa6c60f04cc4ab102d7f82705ab4":{
      "scriptId":"u21"},
    "78d60e743b0f40c58d0c8eeaf9f0f4fb":{
      "scriptId":"u22"},
    "1e658f39e853444082b4c73ea4265053":{
      "scriptId":"u23"},
    "9969958ac84e403a8b10158ee6ecdb80":{
      "scriptId":"u24"},
    "5017a41ae969423db9bec44d0e65959d":{
      "scriptId":"u25"},
    "bd1199960f3d47638c3845d0c570d2a8":{
      "scriptId":"u26"},
    "4e02e89f1da64fb1b2776d4f939c69de":{
      "scriptId":"u27"},
    "5fba01fa18754fa88637719f81045edd":{
      "scriptId":"u28"},
    "ff325ad1d5134379a96f63c6bdb76f2c":{
      "scriptId":"u29"},
    "f00f6899e17947dc8252c7cb16e8b1b0":{
      "scriptId":"u30"},
    "c4c6e00d9957415bb17f446e4eaaa8e0":{
      "scriptId":"u31"},
    "bc65272e48ad476282c653a2db7f5466":{
      "scriptId":"u32"},
    "d3fe7386fe6749ec83af65122ab62f8b":{
      "scriptId":"u33"},
    "fd811ed6ad274b1eb38ee7acb20446a7":{
      "scriptId":"u34"},
    "010c9e89bb0f40fda0c5b30ecad76603":{
      "scriptId":"u35"},
    "bf60aa0a72ff438ba33c885fa95ae95e":{
      "scriptId":"u36"},
    "7d8c4dcf499445b2b88c15c1de946442":{
      "scriptId":"u37"},
    "6a6a0d1e73e34804a389661d3f1d2570":{
      "scriptId":"u38"},
    "acdd8752d35944a7ad3ed728840c5c20":{
      "scriptId":"u39"},
    "532cffd182c8435a91a083811d6aab91":{
      "scriptId":"u40"},
    "5e1ebac77bef47df829699c2d3e606ee":{
      "scriptId":"u41"},
    "6fc493e7e6f84146a0197a2bc89117fa":{
      "scriptId":"u42"},
    "14d254e2d4a54cdf9d2724857235cfac":{
      "scriptId":"u43"},
    "3d1552fd5339490e8f900c212cc0fa62":{
      "scriptId":"u44"},
    "69bde93244eb49e68809f3defbaffe57":{
      "scriptId":"u45"},
    "9c4e9970adb04cacac8e94192d5d13b2":{
      "scriptId":"u46"},
    "2d55f4f542c7463380a6bfc4bebad5ad":{
      "scriptId":"u47"},
    "b331705568df437394b70276a33283d3":{
      "scriptId":"u48"},
    "da6caa73d0924f9d9dbf1ccf698e2ff7":{
      "scriptId":"u49"},
    "6b09742a94f84638b38d45d3251d8920":{
      "scriptId":"u50"},
    "5309180970aa488bb5eec91a307b8666":{
      "scriptId":"u51"},
    "adf5d336229046439535c57e2471befb":{
      "scriptId":"u52"},
    "56d298ebd063453996f49c65457df482":{
      "scriptId":"u53"},
    "65e0f5a3242c44f28ac85cf95da89a2e":{
      "scriptId":"u54"},
    "acd6ac5cef5940bb84f7a988fd64db62":{
      "scriptId":"u55"},
    "83e345c7bfe745fbb0ec54e3f0749e28":{
      "scriptId":"u56"},
    "d04643dafde84d84857abb21fa183971":{
      "scriptId":"u57"},
    "e9210e332e58426b98ac02534eac5c30":{
      "scriptId":"u58"},
    "03e795df9ade4117a7ac7cffaf3ac8a5":{
      "scriptId":"u59"}}});