$axure.loadCurrentPage({
  "url":"充值支付宝.html",
  "generationDate":new Date(1385387514421.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f9b8021ad3240ba82045c2657d5f79f",
    "type":"Axure:Page",
    "name":"充值支付宝",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6d8ca800494d4cd88d4081898875d6db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":1150,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3a1151099ce4be5a24af6eba4d496d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":1150,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u0.png"}},
{
          "id":"5dafaaa03e2a43deac3f0a59d07e77f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":251},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"799afaa3a6cd4fcb8de2067ed5127ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":251},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21eeb69a6a79470d82e1a7ee07aa35a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":287},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8580806e1c15495480c2899e4f20d0d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":287},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"611aa7b77d0a4871a5fefdf2e9b341f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":412,
              "y":253},
            "size":{
              "width":50,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f40ee3f0ef40fc9794e8f5e44977f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":412,
                  "y":253},
                "size":{
                  "width":50,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d73a677638064267afc609edce5b8ec5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":255},
            "size":{
              "width":108,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c705f13459f5485c89719273966319f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":255},
                "size":{
                  "width":108,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75d4a62e4e214b259c35e0d057c4ec2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":412,
              "y":291},
            "size":{
              "width":51,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d281e4bb351b4e64869986279319b97b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":412,
                  "y":291},
                "size":{
                  "width":51,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8c27de013314970897fb0fe87dd4b70",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文宋体 Regular', '华文宋体'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":310,
              "y":212},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa73c243f9b74444b65e21dc19efbd64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文宋体 Regular', '华文宋体'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":310,
                  "y":212},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dff5dbb89c5844a0929e6091126be112",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":355},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25174e699d7a4a9198acd5ec4eb347f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":355},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b540720daf946d3bf3147d728bf920e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":443},
            "size":{
              "width":100,
              "height":52}},
          "adaptiveStyles":{
}},
{
          "id":"f68db58de06141c7b3a4f6f639b819a2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":357},
            "size":{
              "width":150,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"e93562f276d9473d8b049ba378fc77c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":202},
            "size":{
              "width":223,
              "height":168},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb71b5ece8f4e44939ed435b9d4409b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":202},
                "size":{
                  "width":223,
                  "height":168},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u18.png"}},
{
          "id":"cc1feb1c1dad41b8bab7a35d51ffaeb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":601,
              "y":230},
            "size":{
              "width":66,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd327a3c1d6b4f3b8de6d62e67f3d363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":601,
                  "y":230},
                "size":{
                  "width":66,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fb5d6a5563f4287ae73d2b8a33f6b31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":601,
              "y":264},
            "size":{
              "width":170,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bca19976535481192522cce6f561ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":601,
                  "y":264},
                "size":{
                  "width":170,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1960eb2ee18a425cb867a1c83f0b1296",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":401},
            "size":{
              "width":223,
              "height":168},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b84ca3e608a4e839c395b4ca214b165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":401},
                "size":{
                  "width":223,
                  "height":168},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u18.png"}},
{
          "id":"98258de5106347bebf0f491c6d492026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":612,
              "y":426},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21670dc67c5942b59f027ad7f7c0f81c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":612,
                  "y":426},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ef03b2badc24027b11af5410dc1f819",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":460},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd055e377d741b7b08379a8d9fdd707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":460},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"215170300ad9434fb491866d061e1245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":499},
            "size":{
              "width":196,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"246f467a244d4891a8ef36421bc56332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":499},
                "size":{
                  "width":196,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a11720448fa4ea292200d1df83734a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":537},
            "size":{
              "width":144,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8e7d6c1b55c4f87b13ccf3d1af0745a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":537},
                "size":{
                  "width":144,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6df138ef33854f6cb0dedc48943bd2cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":172},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c1f73c7d32243458e15c0378df8879e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":172},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u34.png"}},
{
          "id":"df78ac0af03347b8a5469de77de38382",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":224},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02e02ccfc8124d2688851b8f015c151d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":224},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值易宝充值卡",
                      "target":{
                        "targetType":"page",
                        "url":"充值易宝充值卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值支付宝/u36.png"}},
{
          "id":"2e198ef590b1433e8f078a962fedfd3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":276},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8451c61a0f4ed381d9b189be39f752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":276},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值银联",
                      "target":{
                        "targetType":"page",
                        "url":"充值银联.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值支付宝/u36.png"}},
{
          "id":"2ea539a05e3b413eae77166567d0ffad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":40,
              "y":90},
            "size":{
              "width":1150,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ccf601760ce4862bf358dc996a27462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":40,
                  "y":90},
                "size":{
                  "width":1150,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u40.png"}},
{
          "id":"5c4720cb77984b57982d35bce5fc53f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":337,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c5595267ba44bfa1649dd82a5cba8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":337,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-成功登录",
                      "target":{
                        "targetType":"page",
                        "url":"主页-成功登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e96ef2a2d05f41ea80754ee9db0c8c9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a3733f6010d451488abab2db4f13d17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0bb44ed5d9f4c8aa3e1dc8058da4c09",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":102},
            "size":{
              "width":10,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页-直播大厅/u19_line.png"}},
{
          "id":"f47b55b041f24556b828c546d981fc61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0x56F2F2F2},
            "location":{
              "x":140,
              "y":102},
            "size":{
              "width":170,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4394a2f621044e1b90d40b184cbb88b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0x56F2F2F2},
                "location":{
                  "x":140,
                  "y":102},
                "size":{
                  "width":170,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u20.png"}},
{
          "id":"65bc7a05aa7e465599fed762077e428d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":74},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7798e4592884d40aab6caee465d9072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":74},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53880191910b475ab031544ab746deb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":74},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bf19062addf4435a8334793a2929020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1031,
                  "y":74},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5f913c9626b46f7a8d87e428740e391",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1153,
              "y":74},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff78c1dbc4f144a7b8afe81c471d2cc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1153,
                  "y":74},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"772dd6eaa5204389b1991a0ae336ea42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":264},
            "size":{
              "width":294,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91944a588df148fc953790e9f31fe92c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":264},
                "size":{
                  "width":294,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u283.png"}},
{
          "id":"03be573c929842d3baf66a8da01883ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":201},
            "size":{
              "width":225,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456e0739801e4fc4b9486e88a24648f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":409,
                  "y":201},
                "size":{
                  "width":225,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6d8ca800494d4cd88d4081898875d6db":{
      "scriptId":"u0"},
    "b3a1151099ce4be5a24af6eba4d496d3":{
      "scriptId":"u1"},
    "5dafaaa03e2a43deac3f0a59d07e77f6":{
      "scriptId":"u2"},
    "799afaa3a6cd4fcb8de2067ed5127ad3":{
      "scriptId":"u3"},
    "21eeb69a6a79470d82e1a7ee07aa35a4":{
      "scriptId":"u4"},
    "8580806e1c15495480c2899e4f20d0d0":{
      "scriptId":"u5"},
    "611aa7b77d0a4871a5fefdf2e9b341f2":{
      "scriptId":"u6"},
    "31f40ee3f0ef40fc9794e8f5e44977f3":{
      "scriptId":"u7"},
    "d73a677638064267afc609edce5b8ec5":{
      "scriptId":"u8"},
    "c705f13459f5485c89719273966319f4":{
      "scriptId":"u9"},
    "75d4a62e4e214b259c35e0d057c4ec2a":{
      "scriptId":"u10"},
    "d281e4bb351b4e64869986279319b97b":{
      "scriptId":"u11"},
    "d8c27de013314970897fb0fe87dd4b70":{
      "scriptId":"u12"},
    "aa73c243f9b74444b65e21dc19efbd64":{
      "scriptId":"u13"},
    "dff5dbb89c5844a0929e6091126be112":{
      "scriptId":"u14"},
    "25174e699d7a4a9198acd5ec4eb347f3":{
      "scriptId":"u15"},
    "1b540720daf946d3bf3147d728bf920e":{
      "scriptId":"u16"},
    "f68db58de06141c7b3a4f6f639b819a2":{
      "scriptId":"u17"},
    "e93562f276d9473d8b049ba378fc77c6":{
      "scriptId":"u18"},
    "6cb71b5ece8f4e44939ed435b9d4409b":{
      "scriptId":"u19"},
    "cc1feb1c1dad41b8bab7a35d51ffaeb4":{
      "scriptId":"u20"},
    "dd327a3c1d6b4f3b8de6d62e67f3d363":{
      "scriptId":"u21"},
    "0fb5d6a5563f4287ae73d2b8a33f6b31":{
      "scriptId":"u22"},
    "7bca19976535481192522cce6f561ecc":{
      "scriptId":"u23"},
    "1960eb2ee18a425cb867a1c83f0b1296":{
      "scriptId":"u24"},
    "4b84ca3e608a4e839c395b4ca214b165":{
      "scriptId":"u25"},
    "98258de5106347bebf0f491c6d492026":{
      "scriptId":"u26"},
    "21670dc67c5942b59f027ad7f7c0f81c":{
      "scriptId":"u27"},
    "6ef03b2badc24027b11af5410dc1f819":{
      "scriptId":"u28"},
    "2bd055e377d741b7b08379a8d9fdd707":{
      "scriptId":"u29"},
    "215170300ad9434fb491866d061e1245":{
      "scriptId":"u30"},
    "246f467a244d4891a8ef36421bc56332":{
      "scriptId":"u31"},
    "2a11720448fa4ea292200d1df83734a6":{
      "scriptId":"u32"},
    "d8e7d6c1b55c4f87b13ccf3d1af0745a":{
      "scriptId":"u33"},
    "6df138ef33854f6cb0dedc48943bd2cb":{
      "scriptId":"u34"},
    "6c1f73c7d32243458e15c0378df8879e":{
      "scriptId":"u35"},
    "df78ac0af03347b8a5469de77de38382":{
      "scriptId":"u36"},
    "02e02ccfc8124d2688851b8f015c151d":{
      "scriptId":"u37"},
    "2e198ef590b1433e8f078a962fedfd3f":{
      "scriptId":"u38"},
    "6b8451c61a0f4ed381d9b189be39f752":{
      "scriptId":"u39"},
    "2ea539a05e3b413eae77166567d0ffad":{
      "scriptId":"u40"},
    "1ccf601760ce4862bf358dc996a27462":{
      "scriptId":"u41"},
    "5c4720cb77984b57982d35bce5fc53f7":{
      "scriptId":"u42"},
    "90c5595267ba44bfa1649dd82a5cba8a":{
      "scriptId":"u43"},
    "e96ef2a2d05f41ea80754ee9db0c8c9a":{
      "scriptId":"u44"},
    "3a3733f6010d451488abab2db4f13d17":{
      "scriptId":"u45"},
    "a0bb44ed5d9f4c8aa3e1dc8058da4c09":{
      "scriptId":"u46"},
    "f47b55b041f24556b828c546d981fc61":{
      "scriptId":"u47"},
    "f4394a2f621044e1b90d40b184cbb88b":{
      "scriptId":"u48"},
    "65bc7a05aa7e465599fed762077e428d":{
      "scriptId":"u49"},
    "e7798e4592884d40aab6caee465d9072":{
      "scriptId":"u50"},
    "53880191910b475ab031544ab746deb5":{
      "scriptId":"u51"},
    "4bf19062addf4435a8334793a2929020":{
      "scriptId":"u52"},
    "a5f913c9626b46f7a8d87e428740e391":{
      "scriptId":"u53"},
    "ff78c1dbc4f144a7b8afe81c471d2cc3":{
      "scriptId":"u54"},
    "772dd6eaa5204389b1991a0ae336ea42":{
      "scriptId":"u55"},
    "91944a588df148fc953790e9f31fe92c":{
      "scriptId":"u56"},
    "03be573c929842d3baf66a8da01883ea":{
      "scriptId":"u57"},
    "456e0739801e4fc4b9486e88a24648f4":{
      "scriptId":"u58"}}});