$axure.loadCurrentPage({
  "url":"充值银联.html",
  "generationDate":new Date(1385387515390.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e05dcada7aa4de9a1ec4bb1b59f258f",
    "type":"Axure:Page",
    "name":"充值银联",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"83fbe99524e14a5f896d1a8b8f520e7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":1150,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76f464c7eca4641a22956f5e2f5ec9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":1150,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u0.png"}},
{
          "id":"6a499edc71024936aa1c3863ee6861ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":251},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb129b62fbc4abbb813cf94f14ef568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":251},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d61453fa5b624a6281013a49bc0fbe53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":287},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb7e444fe1f64b5e9a2ad6b014c26ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":287},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1be0aba0836450d924cb4f8bb133fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":412,
              "y":253},
            "size":{
              "width":50,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41e91912e02a48ed8a57d8ed780185f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":412,
                  "y":253},
                "size":{
                  "width":50,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e9d4ab2c03b4643b5b0e57931362f31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":255},
            "size":{
              "width":108,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ceebad127b3460db319694d4e92f688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":255},
                "size":{
                  "width":108,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5559a9133d2e4033b4e3de93ee3cc69b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":412,
              "y":291},
            "size":{
              "width":51,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c060886c3a1f4459a477fa3d8b7d7ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":412,
                  "y":291},
                "size":{
                  "width":51,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85bea1eaa43144c5b1bc4e5593cd91cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文宋体 Regular', '华文宋体'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":310,
              "y":212},
            "size":{
              "width":81,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"611bc7f3d59440e2b04094e63cf6074a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文宋体 Regular', '华文宋体'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":310,
                  "y":212},
                "size":{
                  "width":81,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7024ae6345aa4b08a0d57332cba4b7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":355},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214e14d13d7243168b43aa976ed01fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":355},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5507b6ab4340bb9e11a929b0c762ac",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":658},
            "size":{
              "width":100,
              "height":52}},
          "adaptiveStyles":{
}},
{
          "id":"4a23bde5fac74167a1952775f711a44f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":357},
            "size":{
              "width":150,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"2a72fda3996d4fc893eff1c43ad58991",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":60,
              "y":164},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66a445035bd94ae7a87c012c5a86768e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":60,
                  "y":164},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值易宝充值卡/u15.png"}},
{
          "id":"e082ae30fda442f1a0da62fcfbab435f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":60,
              "y":216},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddcee9214bdb4b768a478a2dfdcc4824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":60,
                  "y":216},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值易宝充值卡",
                      "target":{
                        "targetType":"page",
                        "url":"充值易宝充值卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值易宝充值卡/u15.png"}},
{
          "id":"6903793f0cc84b81a82565de769c0d06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":268},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef01243fcbf4aacb125ea521ce60d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":268},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u34.png"}},
{
          "id":"f798aa7ddf39437996fee6549861ce0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":40,
              "y":90},
            "size":{
              "width":1150,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32becff08a4d49fdba373684b1dcad22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":40,
                  "y":90},
                "size":{
                  "width":1150,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u40.png"}},
{
          "id":"4e382579378d4b90ba72e49e96a5100d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":337,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae61901511c243b388d99eb30a7b855c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":337,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-成功登录",
                      "target":{
                        "targetType":"page",
                        "url":"主页-成功登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5418c12854a94177862539a15de5ee86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea096735c3b74560bc67e99e223607f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9eec70c69ed4055b3e0d9bf4d91f249",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":102},
            "size":{
              "width":10,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页-直播大厅/u19_line.png"}},
{
          "id":"16ed8cfc0d6d410cb4ba53ba44b1557a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0x56F2F2F2},
            "location":{
              "x":140,
              "y":102},
            "size":{
              "width":170,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f637e6007e14c60a0b3351369c77fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0x56F2F2F2},
                "location":{
                  "x":140,
                  "y":102},
                "size":{
                  "width":170,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u20.png"}},
{
          "id":"2d73d3c330db4ab8bebcd2188cbae6fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":74},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f135c23aa1742f9a80494dad2463b99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":74},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eccd27a6860e44d1a29556c63199cf87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":74},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ca2c1a7dfdf47fb8ff954a3682e1975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1031,
                  "y":74},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0f7c6d425c84ed2975b2b6664386df4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1153,
              "y":74},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee0dda7118d4d40aa95b35d54fd11e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1153,
                  "y":74},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08f480c51cf04abf902127ad9055e843",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "location":{
              "x":311,
              "y":392},
            "size":{
              "width":570,
              "height":248},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219e92ce24d34f428dbd33edc3827e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "location":{
                  "x":311,
                  "y":392},
                "size":{
                  "width":570,
                  "height":248},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值银联/u39.png"}},
{
          "id":"23e1e15c6a1b44f6be6b5f11d492f787",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":658,
              "y":222},
            "size":{
              "width":223,
              "height":160},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f2f0333d5e42619d1c9f3fbf37ff1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":658,
                  "y":222},
                "size":{
                  "width":223,
                  "height":160},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值易宝充值卡/u42.png"}},
{
          "id":"df019d91102d42bd9af1eb852770785c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":678,
              "y":246},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf4d1b24f9d41a58fe22ce0f8ddbca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":678,
                  "y":246},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00cfeb30cf4840b9aa70ac46833e368f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":678,
              "y":279},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d820f0659fe54a6a918a02ce58b1b22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":678,
                  "y":279},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e4a17c1a88842918f9f2e10cb369cfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":678,
              "y":316},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9d620ccdea04d218d78b85d0a984d87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":678,
                  "y":316},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"299ebd2b369a4a8583bd8ad6c5b9d8a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":678,
              "y":352},
            "size":{
              "width":144,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d30dd676c1241edb8b38f8716c9a1e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":678,
                  "y":352},
                "size":{
                  "width":144,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99c2574ec8f84de1829113bba4d4bc15",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":437},
            "size":{
              "width":448,
              "height":158}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b30398542914409ebc71eae1c19785c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":437},
                "size":{
                  "width":448,
                  "height":158}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值银联/u51.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "83fbe99524e14a5f896d1a8b8f520e7a":{
      "scriptId":"u0"},
    "c76f464c7eca4641a22956f5e2f5ec9c":{
      "scriptId":"u1"},
    "6a499edc71024936aa1c3863ee6861ab":{
      "scriptId":"u2"},
    "4bb129b62fbc4abbb813cf94f14ef568":{
      "scriptId":"u3"},
    "d61453fa5b624a6281013a49bc0fbe53":{
      "scriptId":"u4"},
    "cb7e444fe1f64b5e9a2ad6b014c26ebc":{
      "scriptId":"u5"},
    "f1be0aba0836450d924cb4f8bb133fa8":{
      "scriptId":"u6"},
    "41e91912e02a48ed8a57d8ed780185f4":{
      "scriptId":"u7"},
    "7e9d4ab2c03b4643b5b0e57931362f31":{
      "scriptId":"u8"},
    "4ceebad127b3460db319694d4e92f688":{
      "scriptId":"u9"},
    "5559a9133d2e4033b4e3de93ee3cc69b":{
      "scriptId":"u10"},
    "c060886c3a1f4459a477fa3d8b7d7ba3":{
      "scriptId":"u11"},
    "85bea1eaa43144c5b1bc4e5593cd91cf":{
      "scriptId":"u12"},
    "611bc7f3d59440e2b04094e63cf6074a":{
      "scriptId":"u13"},
    "7024ae6345aa4b08a0d57332cba4b7cd":{
      "scriptId":"u14"},
    "214e14d13d7243168b43aa976ed01fd0":{
      "scriptId":"u15"},
    "0c5507b6ab4340bb9e11a929b0c762ac":{
      "scriptId":"u16"},
    "4a23bde5fac74167a1952775f711a44f":{
      "scriptId":"u17"},
    "2a72fda3996d4fc893eff1c43ad58991":{
      "scriptId":"u18"},
    "66a445035bd94ae7a87c012c5a86768e":{
      "scriptId":"u19"},
    "e082ae30fda442f1a0da62fcfbab435f":{
      "scriptId":"u20"},
    "ddcee9214bdb4b768a478a2dfdcc4824":{
      "scriptId":"u21"},
    "6903793f0cc84b81a82565de769c0d06":{
      "scriptId":"u22"},
    "2ef01243fcbf4aacb125ea521ce60d2f":{
      "scriptId":"u23"},
    "f798aa7ddf39437996fee6549861ce0c":{
      "scriptId":"u24"},
    "32becff08a4d49fdba373684b1dcad22":{
      "scriptId":"u25"},
    "4e382579378d4b90ba72e49e96a5100d":{
      "scriptId":"u26"},
    "ae61901511c243b388d99eb30a7b855c":{
      "scriptId":"u27"},
    "5418c12854a94177862539a15de5ee86":{
      "scriptId":"u28"},
    "ea096735c3b74560bc67e99e223607f8":{
      "scriptId":"u29"},
    "e9eec70c69ed4055b3e0d9bf4d91f249":{
      "scriptId":"u30"},
    "16ed8cfc0d6d410cb4ba53ba44b1557a":{
      "scriptId":"u31"},
    "0f637e6007e14c60a0b3351369c77fc6":{
      "scriptId":"u32"},
    "2d73d3c330db4ab8bebcd2188cbae6fa":{
      "scriptId":"u33"},
    "8f135c23aa1742f9a80494dad2463b99":{
      "scriptId":"u34"},
    "eccd27a6860e44d1a29556c63199cf87":{
      "scriptId":"u35"},
    "6ca2c1a7dfdf47fb8ff954a3682e1975":{
      "scriptId":"u36"},
    "a0f7c6d425c84ed2975b2b6664386df4":{
      "scriptId":"u37"},
    "aee0dda7118d4d40aa95b35d54fd11e6":{
      "scriptId":"u38"},
    "08f480c51cf04abf902127ad9055e843":{
      "scriptId":"u39"},
    "219e92ce24d34f428dbd33edc3827e26":{
      "scriptId":"u40"},
    "23e1e15c6a1b44f6be6b5f11d492f787":{
      "scriptId":"u41"},
    "07f2f0333d5e42619d1c9f3fbf37ff1b":{
      "scriptId":"u42"},
    "df019d91102d42bd9af1eb852770785c":{
      "scriptId":"u43"},
    "8cf4d1b24f9d41a58fe22ce0f8ddbca7":{
      "scriptId":"u44"},
    "00cfeb30cf4840b9aa70ac46833e368f":{
      "scriptId":"u45"},
    "d820f0659fe54a6a918a02ce58b1b22b":{
      "scriptId":"u46"},
    "4e4a17c1a88842918f9f2e10cb369cfc":{
      "scriptId":"u47"},
    "a9d620ccdea04d218d78b85d0a984d87":{
      "scriptId":"u48"},
    "299ebd2b369a4a8583bd8ad6c5b9d8a9":{
      "scriptId":"u49"},
    "2d30dd676c1241edb8b38f8716c9a1e9":{
      "scriptId":"u50"},
    "99c2574ec8f84de1829113bba4d4bc15":{
      "scriptId":"u51"},
    "b30398542914409ebc71eae1c19785c3":{
      "scriptId":"u52"}}});