$axure.loadCurrentPage({
  "url":"充值易宝充值卡.html",
  "generationDate":new Date(1385387514921.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9478bc8cbcc14e4d8d464e152baa10fb",
    "type":"Axure:Page",
    "name":"充值易宝充值卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"254e87cfeed942d281bf17c7e0437f63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":1150,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99fa874b31a04e38886f93badb735480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":1150,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u0.png"}},
{
          "id":"b4cdd6628f2d4312871a4f95a591d7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":251},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb628eb930f4127b3f2d961953b9a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":251},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f3200275bc041478bb4dd30a8bd6618",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":311,
              "y":287},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb12648e823b42c296ce859e96ee125d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":311,
                  "y":287},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b318b4183ea744e48591316f471112b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":412,
              "y":253},
            "size":{
              "width":50,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f74e665d7ec4ef2b3d6095430e22d52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":412,
                  "y":253},
                "size":{
                  "width":50,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e5c2b402b1d419580dd63f759ba2d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":255},
            "size":{
              "width":108,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f2817f5c3884a9491798ac0d54317aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":255},
                "size":{
                  "width":108,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76d8718c40884363badf28a9a6d9a262",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":412,
              "y":291},
            "size":{
              "width":51,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59c37df185e9491ea35b160eb5f9be44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":412,
                  "y":291},
                "size":{
                  "width":51,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fb4de4c865642a9b0f91606c0e1ab63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文宋体 Regular', '华文宋体'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":310,
              "y":212},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae2633a651334aef8f9f8b0d0ea7fcec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文宋体 Regular', '华文宋体'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":310,
                  "y":212},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1ab798baa164119a1b0f163e5541eea",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":532},
            "size":{
              "width":100,
              "height":52}},
          "adaptiveStyles":{
}},
{
          "id":"9f48bd6fee3e42bb9c944031fa5511cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":60,
              "y":170},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"349140618de04408a187fa5119b00a79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":60,
                  "y":170},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值易宝充值卡/u15.png"}},
{
          "id":"d35586d97a92498899c1b0fb46deaf75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":222},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90ff62c0913a44babf9944bd65558690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":222},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u34.png"}},
{
          "id":"33f8d71dfc0d4b6dbefdc07e6787285a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":274},
            "size":{
              "width":200,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"420988e7c24247aeadc36db53b32743c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":274},
                "size":{
                  "width":200,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值银联",
                      "target":{
                        "targetType":"page",
                        "url":"充值银联.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值支付宝/u36.png"}},
{
          "id":"2f294f60ef59485fb4b8cddf101c1637",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":40,
              "y":90},
            "size":{
              "width":1150,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db0275e97803458cb4984760fe707fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":40,
                  "y":90},
                "size":{
                  "width":1150,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值支付宝/u40.png"}},
{
          "id":"a381588430f94cbf9ad699b62e582e64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":337,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"671d0b7d1b5043ebb3aff7adfc6f9541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":337,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-成功登录",
                      "target":{
                        "targetType":"page",
                        "url":"主页-成功登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30c93ef9069e440398f4f107196353e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40937857aee44b1baca63dc071ae70d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f90ea56d5b644deae26deed8ca53ee1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":102},
            "size":{
              "width":10,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页-直播大厅/u19_line.png"}},
{
          "id":"5931107e6d59412e83fcd2c2b529bc46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0x56F2F2F2},
            "location":{
              "x":140,
              "y":102},
            "size":{
              "width":170,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08957919e06441dbaf6ea337a20e402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0x56F2F2F2},
                "location":{
                  "x":140,
                  "y":102},
                "size":{
                  "width":170,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u20.png"}},
{
          "id":"0a4445bd75ef422f8e9c2bee003ea9ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":74},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f9a1f442e0447eb2219335839d901e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":74},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98c3c014df3847949e6848ca61c15b88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1031,
              "y":74},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434d848ae02e4f1eb43cdf5bf4313d29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1031,
                  "y":74},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f5e6b8ae12e46cf80d43b3f52db3696",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1153,
              "y":74},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a80a0fd445a54ac48bee09a5a554c6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1153,
                  "y":74},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b468399ba9bb4aeab81672265f7d0c0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":212},
            "size":{
              "width":223,
              "height":170},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ccad7a0dd7444e9b37464564190b3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":212},
                "size":{
                  "width":223,
                  "height":170},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值易宝充值卡/u36.png"}},
{
          "id":"7aa498ccc1cc45feba3fbd0523caafed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":629,
              "y":239},
            "size":{
              "width":66,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50cc7e47ae594cc5b84062c1fd1448bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":629,
                  "y":239},
                "size":{
                  "width":66,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d49047bf0fbc424db1993ae1101ed5f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":261},
            "size":{
              "width":183,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cbf8c96e70c46858b7a9cb33ba20253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":261},
                "size":{
                  "width":183,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b545821054f43b8a17cc801dcb79c85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":402},
            "size":{
              "width":223,
              "height":160},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457b43052b884da881e554b3e81423b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":402},
                "size":{
                  "width":223,
                  "height":160},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值易宝充值卡/u42.png"}},
{
          "id":"1860ba1bd59f43009e2e8890f35271be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":640,
              "y":426},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64832e97c2464912a4ce63500c280658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":426},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaac97841c7b4b2b922a647885d2451e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":459},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea0c9d1ee1442c99520ff33c2e7900f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":459},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72a5510035374b27a3cdd4f0f17a02c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":496},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b38279c143c4bc5b89b796d6ca132d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":496},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a983c962bed4cea8c9881c812392b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":532},
            "size":{
              "width":144,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f40ae2be8841c7a1bc0046535fd91f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":532},
                "size":{
                  "width":144,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b673e06aadd41499a74914de44c4085",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":313,
              "y":367},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f097f6ccbeff41a9b6dbd9ad98b8f688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":313,
                  "y":367},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b2627401b145ebb41cabc4d01a50bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":411},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30a6129d73c46eb9f5b7eab9ffdcec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":384,
                  "y":411},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值易宝充值卡/u54.png"}},
{
          "id":"04107b7d184b4b868bb6b5b08637cbb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":313,
              "y":418},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3367f3fa222403b80bcc782d85dcfb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":313,
                  "y":418},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6ee0a052cd94ce48a14267fbd45183e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":461},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937520f9a8a54c44ba3a836d9e7d9e7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":384,
                  "y":461},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值易宝充值卡/u54.png"}},
{
          "id":"6633db450b9c4e9fbb3f53084fee4b64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":313,
              "y":465},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdaae8b9b64a4e189d52edcb3557790e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":313,
                  "y":465},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afdbb99d7cc24375b41c484fec2da1ee",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":321},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53fe80cab76c42c58aacf735d880ce22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":382,
                  "y":321},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9114b9b4e0684170babef3608ded2250",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":321},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e735b601b4dc4a19a4055dd9cbeceafb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":321},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3f7c02665ecb459d9976c93ecec9564e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":321},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb3e57de7b9d4c48a1ee916a5bfb33ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":321},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"85691ddf5d1448699383052f3ccbc417",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":311,
              "y":321},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bdc5314c8424bce944658fe1ad4fdbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":311,
                  "y":321},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcd97e1be4db4e239ccc8b4ae6a3784f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":360},
            "size":{
              "width":150,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"f32ae52f014a4a2588e3e85ffc693ec0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":321},
            "size":{
              "width":294,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3f3803c75b643529984d8221ad5403b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":321},
                "size":{
                  "width":294,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u283.png"}},
{
          "id":"e1bf2d7784ec44aca1b11ad115974a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":284},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ce3a8902c84de8b55e6e79a503e5bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":284},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "254e87cfeed942d281bf17c7e0437f63":{
      "scriptId":"u0"},
    "99fa874b31a04e38886f93badb735480":{
      "scriptId":"u1"},
    "b4cdd6628f2d4312871a4f95a591d7cd":{
      "scriptId":"u2"},
    "eeb628eb930f4127b3f2d961953b9a01":{
      "scriptId":"u3"},
    "9f3200275bc041478bb4dd30a8bd6618":{
      "scriptId":"u4"},
    "fb12648e823b42c296ce859e96ee125d":{
      "scriptId":"u5"},
    "b318b4183ea744e48591316f471112b8":{
      "scriptId":"u6"},
    "5f74e665d7ec4ef2b3d6095430e22d52":{
      "scriptId":"u7"},
    "1e5c2b402b1d419580dd63f759ba2d30":{
      "scriptId":"u8"},
    "4f2817f5c3884a9491798ac0d54317aa":{
      "scriptId":"u9"},
    "76d8718c40884363badf28a9a6d9a262":{
      "scriptId":"u10"},
    "59c37df185e9491ea35b160eb5f9be44":{
      "scriptId":"u11"},
    "2fb4de4c865642a9b0f91606c0e1ab63":{
      "scriptId":"u12"},
    "ae2633a651334aef8f9f8b0d0ea7fcec":{
      "scriptId":"u13"},
    "a1ab798baa164119a1b0f163e5541eea":{
      "scriptId":"u14"},
    "9f48bd6fee3e42bb9c944031fa5511cf":{
      "scriptId":"u15"},
    "349140618de04408a187fa5119b00a79":{
      "scriptId":"u16"},
    "d35586d97a92498899c1b0fb46deaf75":{
      "scriptId":"u17"},
    "90ff62c0913a44babf9944bd65558690":{
      "scriptId":"u18"},
    "33f8d71dfc0d4b6dbefdc07e6787285a":{
      "scriptId":"u19"},
    "420988e7c24247aeadc36db53b32743c":{
      "scriptId":"u20"},
    "2f294f60ef59485fb4b8cddf101c1637":{
      "scriptId":"u21"},
    "db0275e97803458cb4984760fe707fc3":{
      "scriptId":"u22"},
    "a381588430f94cbf9ad699b62e582e64":{
      "scriptId":"u23"},
    "671d0b7d1b5043ebb3aff7adfc6f9541":{
      "scriptId":"u24"},
    "30c93ef9069e440398f4f107196353e4":{
      "scriptId":"u25"},
    "40937857aee44b1baca63dc071ae70d3":{
      "scriptId":"u26"},
    "5f90ea56d5b644deae26deed8ca53ee1":{
      "scriptId":"u27"},
    "5931107e6d59412e83fcd2c2b529bc46":{
      "scriptId":"u28"},
    "b08957919e06441dbaf6ea337a20e402":{
      "scriptId":"u29"},
    "0a4445bd75ef422f8e9c2bee003ea9ad":{
      "scriptId":"u30"},
    "44f9a1f442e0447eb2219335839d901e":{
      "scriptId":"u31"},
    "98c3c014df3847949e6848ca61c15b88":{
      "scriptId":"u32"},
    "434d848ae02e4f1eb43cdf5bf4313d29":{
      "scriptId":"u33"},
    "9f5e6b8ae12e46cf80d43b3f52db3696":{
      "scriptId":"u34"},
    "a80a0fd445a54ac48bee09a5a554c6d0":{
      "scriptId":"u35"},
    "b468399ba9bb4aeab81672265f7d0c0a":{
      "scriptId":"u36"},
    "1ccad7a0dd7444e9b37464564190b3b6":{
      "scriptId":"u37"},
    "7aa498ccc1cc45feba3fbd0523caafed":{
      "scriptId":"u38"},
    "50cc7e47ae594cc5b84062c1fd1448bf":{
      "scriptId":"u39"},
    "d49047bf0fbc424db1993ae1101ed5f7":{
      "scriptId":"u40"},
    "1cbf8c96e70c46858b7a9cb33ba20253":{
      "scriptId":"u41"},
    "3b545821054f43b8a17cc801dcb79c85":{
      "scriptId":"u42"},
    "457b43052b884da881e554b3e81423b9":{
      "scriptId":"u43"},
    "1860ba1bd59f43009e2e8890f35271be":{
      "scriptId":"u44"},
    "64832e97c2464912a4ce63500c280658":{
      "scriptId":"u45"},
    "eaac97841c7b4b2b922a647885d2451e":{
      "scriptId":"u46"},
    "fea0c9d1ee1442c99520ff33c2e7900f":{
      "scriptId":"u47"},
    "72a5510035374b27a3cdd4f0f17a02c1":{
      "scriptId":"u48"},
    "7b38279c143c4bc5b89b796d6ca132d8":{
      "scriptId":"u49"},
    "4a983c962bed4cea8c9881c812392b51":{
      "scriptId":"u50"},
    "f6f40ae2be8841c7a1bc0046535fd91f":{
      "scriptId":"u51"},
    "7b673e06aadd41499a74914de44c4085":{
      "scriptId":"u52"},
    "f097f6ccbeff41a9b6dbd9ad98b8f688":{
      "scriptId":"u53"},
    "a9b2627401b145ebb41cabc4d01a50bf":{
      "scriptId":"u54"},
    "d30a6129d73c46eb9f5b7eab9ffdcec0":{
      "scriptId":"u55"},
    "04107b7d184b4b868bb6b5b08637cbb2":{
      "scriptId":"u56"},
    "d3367f3fa222403b80bcc782d85dcfb0":{
      "scriptId":"u57"},
    "b6ee0a052cd94ce48a14267fbd45183e":{
      "scriptId":"u58"},
    "937520f9a8a54c44ba3a836d9e7d9e7d":{
      "scriptId":"u59"},
    "6633db450b9c4e9fbb3f53084fee4b64":{
      "scriptId":"u60"},
    "fdaae8b9b64a4e189d52edcb3557790e":{
      "scriptId":"u61"},
    "afdbb99d7cc24375b41c484fec2da1ee":{
      "scriptId":"u62"},
    "53fe80cab76c42c58aacf735d880ce22":{
      "scriptId":"u63"},
    "9114b9b4e0684170babef3608ded2250":{
      "scriptId":"u64"},
    "e735b601b4dc4a19a4055dd9cbeceafb":{
      "scriptId":"u65"},
    "3f7c02665ecb459d9976c93ecec9564e":{
      "scriptId":"u66"},
    "eb3e57de7b9d4c48a1ee916a5bfb33ae":{
      "scriptId":"u67"},
    "85691ddf5d1448699383052f3ccbc417":{
      "scriptId":"u68"},
    "2bdc5314c8424bce944658fe1ad4fdbf":{
      "scriptId":"u69"},
    "fcd97e1be4db4e239ccc8b4ae6a3784f":{
      "scriptId":"u70"},
    "f32ae52f014a4a2588e3e85ffc693ec0":{
      "scriptId":"u71"},
    "e3f3803c75b643529984d8221ad5403b":{
      "scriptId":"u72"},
    "e1bf2d7784ec44aca1b11ad115974a2e":{
      "scriptId":"u73"},
    "17ce3a8902c84de8b55e6e79a503e5bb":{
      "scriptId":"u74"}}});