$axure.loadCurrentPage({
  "url":"开始直播.html",
  "generationDate":new Date(1385387513515.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d1628c0ef81345b3806c401bf3c89f90",
    "type":"Axure:Page",
    "name":"开始直播",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f134d00fb3c4a8098ebe26dd146b890",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":1020,
              "height":910}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd220be94b543a79958066bc6428639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":40},
                "size":{
                  "width":1020,
                  "height":910}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u0.png"}},
{
          "id":"80a6e7e6c56a4157ae40f7b5f5bd2c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":107},
            "size":{
              "width":830,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54d53e479990436e9905485cbae3f239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":107},
                "size":{
                  "width":830,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u2.png"}},
{
          "id":"8c6d3d2d61be41e2b609b5e25d1f65a1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":117},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fce8e2690d7148fdb427209d1022b6eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":91},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04027e7039d74e30a177f6ced4d54b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":91},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdcc28d9de574261ab867cfbe8842d14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":91},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a540eaffedb4fe381e01f2ca155724f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":91},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b66da91e8c1470faca4e71dfbac9edf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":923,
              "y":91},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55c0c780144f4a558c17cf65072769e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":923,
                  "y":91},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7963dac553ba470a91b6620023bce8bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":129},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"490efb0686214588aee5cdbb62679034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":129},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6d48ab7c9d145a281eb5d4fddfa44b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":170},
            "size":{
              "width":830,
              "height":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"186d3e846b634f1fa05ea0310476250d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":170},
                "size":{
                  "width":830,
                  "height":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u13.png"}},
{
          "id":"20f435b38cd3404d82d0f70505198f54",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":230},
            "size":{
              "width":240,
              "height":330},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98c32d4f026440fabb3a347e62948df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":230},
                "size":{
                  "width":240,
                  "height":330},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u15.png"}},
{
          "id":"b17fd8dc2a764e5e8d64b7092bd1433a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":230},
            "size":{
              "width":87,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf3b56cbcedb4f94a3fe05f452396d06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":230},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u17.png"}},
{
          "id":"026ae0b72f3b4397abb6c4295e29f3c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":230},
            "size":{
              "width":139,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8406f56fb3634b679aff526ec06a5301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":230},
                "size":{
                  "width":139,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u19.png"}},
{
          "id":"2199bf0c554c4ffab26710911a26d07c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":230},
            "size":{
              "width":79,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"355d37f94787435f9e8a9dc69a917fa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":230},
                "size":{
                  "width":79,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u21.png"}},
{
          "id":"d6dcbe4c3ffc406f96f31a8198673a4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":274},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf3704f9bce4bbbbb50488ba7512e75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":274},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfe55477e17d432d97b411cbd19cc68b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":304},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"252b1050bd6248478d42ca6c30220857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":304},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e08b8f0740b4422fb4562e777a5ff879",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":570},
            "size":{
              "width":67,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"320c71f5cde64f10ae4de84504e2c546",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":570},
            "size":{
              "width":230,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb5ba7013f54ecea06f0c00aa2a32ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":570},
                "size":{
                  "width":230,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u28.png"}},
{
          "id":"c47a8782a53e4d41a3485e060207f459",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":570},
            "size":{
              "width":46,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dcdb9b1c92543aa8c06fb486a50b2cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":570},
                "size":{
                  "width":46,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u30.png"}},
{
          "id":"f7cdb1623c9a4ec0bf86e2e1788e4bb9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":570},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"53b0525fb36d4aa1b0bd0672cacdd473",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":570},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f65dea61124d4718b3a8c56ea642be0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":570},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u33.png"}},
{
          "id":"e44c4967d6bc4ebe94441e3c0393c9fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":572},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88558283ea344f7ea18ccf753f92c530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":572},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c85318903f6d4fd2b5fd4c9ede11954d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":572},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"197e56a428a041d38c1cbd6e2c7b9420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":572},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9f8741de4fe4cc7ab27e9856c77a39a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":570},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d4ffda0f80a94e68bf67f4f1637676e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":576},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55201fde29204f73bff70c0d0b554d52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":576},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f56a3bf3e34e46aea14987d1ec0c7029",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":567},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a6d67b3093c3460d8cb522ff97a2ddb4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":572},
            "size":{
              "width":63,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"c9d51c91414647f9a29f601c3283072d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":214},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2366dfba3b2a40a9a4ba2f9e4da40c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":214},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"528ed4fa5b8547ec978dd0c6f66c7f5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05565810d64b4d82a716390b09331066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e75abd16249b48b8a5e466505dabeea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":850},
            "size":{
              "width":1020,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb084c3b65314973854a57572d3b905a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":850},
                "size":{
                  "width":1020,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u48.png"}},
{
          "id":"9909e09007f34c1bb715c4c49489dea5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":911},
            "size":{
              "width":470,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd51c8c9876451ea0e8fc1bd23f12ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":382,
                  "y":911},
                "size":{
                  "width":470,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u256.png"}},
{
          "id":"adf05fa775f04450842da47b45631295",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF515151},
            "location":{
              "x":160,
              "y":230},
            "size":{
              "width":340,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cdcc600e2db46f0969c93a7620e3922",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151},
                "location":{
                  "x":160,
                  "y":230},
                "size":{
                  "width":340,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u52.png"}},
{
          "id":"c9e8fc01bc254e60a7034188ec7aea8b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":338},
            "size":{
              "width":89,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1b7ffbbbab1b4d1b89be1cc48d297cad",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":338},
            "size":{
              "width":89,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"20c110de558e473a8070dc34c9b34974",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":425},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5b3e4228cebb49089d15215cf71c44f3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":567},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e8ec665a151a42198b64bb638eceb2dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":274},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57f7fa94f9d4200a4a3f1e0978d93eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":274},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8f93ed0ad8d40ae82476cbaf0f87052",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":304},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c94fed72914d738538ff7d7d4bff2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":304},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fee38aa2f624baa84781b6900a6bfe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":338},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42e01cc0058e40dca43135e20d36e244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":338},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da309a891852429098bedd22e4026401",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":205},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"13da3ce37c3544899b40cdf0d36ecf6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":610},
            "size":{
              "width":760,
              "height":100},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"157d328fa0bd4afbb6e5432b5668c8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":610},
                "size":{
                  "width":760,
                  "height":100},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u65.png"}},
{
          "id":"879b7c27d7dd4d60a8089d73b3979b02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bf899988eba4f689038ffacf9575431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf3fd1aac47d4866bfb4bc3087e213a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a79baeee24f34bbdba8ac0e18ac14f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f134d00fb3c4a8098ebe26dd146b890":{
      "scriptId":"u0"},
    "3cd220be94b543a79958066bc6428639":{
      "scriptId":"u1"},
    "80a6e7e6c56a4157ae40f7b5f5bd2c64":{
      "scriptId":"u2"},
    "54d53e479990436e9905485cbae3f239":{
      "scriptId":"u3"},
    "8c6d3d2d61be41e2b609b5e25d1f65a1":{
      "scriptId":"u4"},
    "fce8e2690d7148fdb427209d1022b6eb":{
      "scriptId":"u5"},
    "04027e7039d74e30a177f6ced4d54b44":{
      "scriptId":"u6"},
    "cdcc28d9de574261ab867cfbe8842d14":{
      "scriptId":"u7"},
    "4a540eaffedb4fe381e01f2ca155724f":{
      "scriptId":"u8"},
    "0b66da91e8c1470faca4e71dfbac9edf":{
      "scriptId":"u9"},
    "55c0c780144f4a558c17cf65072769e8":{
      "scriptId":"u10"},
    "7963dac553ba470a91b6620023bce8bc":{
      "scriptId":"u11"},
    "490efb0686214588aee5cdbb62679034":{
      "scriptId":"u12"},
    "d6d48ab7c9d145a281eb5d4fddfa44b6":{
      "scriptId":"u13"},
    "186d3e846b634f1fa05ea0310476250d":{
      "scriptId":"u14"},
    "20f435b38cd3404d82d0f70505198f54":{
      "scriptId":"u15"},
    "98c32d4f026440fabb3a347e62948df4":{
      "scriptId":"u16"},
    "b17fd8dc2a764e5e8d64b7092bd1433a":{
      "scriptId":"u17"},
    "bf3b56cbcedb4f94a3fe05f452396d06":{
      "scriptId":"u18"},
    "026ae0b72f3b4397abb6c4295e29f3c3":{
      "scriptId":"u19"},
    "8406f56fb3634b679aff526ec06a5301":{
      "scriptId":"u20"},
    "2199bf0c554c4ffab26710911a26d07c":{
      "scriptId":"u21"},
    "355d37f94787435f9e8a9dc69a917fa9":{
      "scriptId":"u22"},
    "d6dcbe4c3ffc406f96f31a8198673a4c":{
      "scriptId":"u23"},
    "caf3704f9bce4bbbbb50488ba7512e75":{
      "scriptId":"u24"},
    "bfe55477e17d432d97b411cbd19cc68b":{
      "scriptId":"u25"},
    "252b1050bd6248478d42ca6c30220857":{
      "scriptId":"u26"},
    "e08b8f0740b4422fb4562e777a5ff879":{
      "scriptId":"u27"},
    "320c71f5cde64f10ae4de84504e2c546":{
      "scriptId":"u28"},
    "bfb5ba7013f54ecea06f0c00aa2a32ef":{
      "scriptId":"u29"},
    "c47a8782a53e4d41a3485e060207f459":{
      "scriptId":"u30"},
    "1dcdb9b1c92543aa8c06fb486a50b2cc":{
      "scriptId":"u31"},
    "f7cdb1623c9a4ec0bf86e2e1788e4bb9":{
      "scriptId":"u32"},
    "53b0525fb36d4aa1b0bd0672cacdd473":{
      "scriptId":"u33"},
    "f65dea61124d4718b3a8c56ea642be0c":{
      "scriptId":"u34"},
    "e44c4967d6bc4ebe94441e3c0393c9fc":{
      "scriptId":"u35"},
    "88558283ea344f7ea18ccf753f92c530":{
      "scriptId":"u36"},
    "c85318903f6d4fd2b5fd4c9ede11954d":{
      "scriptId":"u37"},
    "197e56a428a041d38c1cbd6e2c7b9420":{
      "scriptId":"u38"},
    "c9f8741de4fe4cc7ab27e9856c77a39a":{
      "scriptId":"u39"},
    "d4ffda0f80a94e68bf67f4f1637676e5":{
      "scriptId":"u40"},
    "55201fde29204f73bff70c0d0b554d52":{
      "scriptId":"u41"},
    "f56a3bf3e34e46aea14987d1ec0c7029":{
      "scriptId":"u42"},
    "a6d67b3093c3460d8cb522ff97a2ddb4":{
      "scriptId":"u43"},
    "c9d51c91414647f9a29f601c3283072d":{
      "scriptId":"u44"},
    "2366dfba3b2a40a9a4ba2f9e4da40c9b":{
      "scriptId":"u45"},
    "528ed4fa5b8547ec978dd0c6f66c7f5e":{
      "scriptId":"u46"},
    "05565810d64b4d82a716390b09331066":{
      "scriptId":"u47"},
    "e75abd16249b48b8a5e466505dabeea1":{
      "scriptId":"u48"},
    "cb084c3b65314973854a57572d3b905a":{
      "scriptId":"u49"},
    "9909e09007f34c1bb715c4c49489dea5":{
      "scriptId":"u50"},
    "4bd51c8c9876451ea0e8fc1bd23f12ba":{
      "scriptId":"u51"},
    "adf05fa775f04450842da47b45631295":{
      "scriptId":"u52"},
    "4cdcc600e2db46f0969c93a7620e3922":{
      "scriptId":"u53"},
    "c9e8fc01bc254e60a7034188ec7aea8b":{
      "scriptId":"u54"},
    "1b7ffbbbab1b4d1b89be1cc48d297cad":{
      "scriptId":"u55"},
    "20c110de558e473a8070dc34c9b34974":{
      "scriptId":"u56"},
    "5b3e4228cebb49089d15215cf71c44f3":{
      "scriptId":"u57"},
    "e8ec665a151a42198b64bb638eceb2dd":{
      "scriptId":"u58"},
    "f57f7fa94f9d4200a4a3f1e0978d93eb":{
      "scriptId":"u59"},
    "d8f93ed0ad8d40ae82476cbaf0f87052":{
      "scriptId":"u60"},
    "f8c94fed72914d738538ff7d7d4bff2f":{
      "scriptId":"u61"},
    "0fee38aa2f624baa84781b6900a6bfe0":{
      "scriptId":"u62"},
    "42e01cc0058e40dca43135e20d36e244":{
      "scriptId":"u63"},
    "da309a891852429098bedd22e4026401":{
      "scriptId":"u64"},
    "13da3ce37c3544899b40cdf0d36ecf6f":{
      "scriptId":"u65"},
    "157d328fa0bd4afbb6e5432b5668c8ff":{
      "scriptId":"u66"},
    "879b7c27d7dd4d60a8089d73b3979b02":{
      "scriptId":"u67"},
    "2bf899988eba4f689038ffacf9575431":{
      "scriptId":"u68"},
    "cf3fd1aac47d4866bfb4bc3087e213a1":{
      "scriptId":"u69"},
    "a79baeee24f34bbdba8ac0e18ac14f53":{
      "scriptId":"u70"}}});