$axure.loadCurrentPage({
  "url":"排行榜.html",
  "generationDate":new Date(1385387516937.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dc92553df1b145319a9cdc9d03ac9bc2",
    "type":"Axure:Page",
    "name":"排行榜",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b05d11e03d141398af0aa81aab8753d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":880,
              "height":810}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea58760b33e47d097fef70c8df7ac7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":880,
                  "height":810}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u0.png"}},
{
          "id":"3a580949755242c38e7d2c052162cf8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":260},
            "size":{
              "width":230,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e97f5dfaa3c04bd9aa571b8682e0cf63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":260},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u2.png"}},
{
          "id":"23a8b2634ac94bc3b0e12b7bbec8a4ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b29b0449d243f8958601962e7af590",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"797c28d2b0f04867a0adc20eb69f9001",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":260},
            "size":{
              "width":230,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa63076c043a4c608415bfbcfe7541e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":260},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u2.png"}},
{
          "id":"2dd054dac489469490013a8e5f6172cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":260},
            "size":{
              "width":240,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b1baf0ea68949acbef3d006167160f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":260},
                "size":{
                  "width":240,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u8.png"}},
{
          "id":"97b79dced86049228ec44b36c1b0e830",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":290},
            "size":{
              "width":230,
              "height":510},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38aa2ed4ea8043dca43e85b20330e0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":290},
                "size":{
                  "width":230,
                  "height":510},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u10.png"}},
{
          "id":"1c53a089eeb54d8d8aa1f8956cf2ce06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":290},
            "size":{
              "width":230,
              "height":510},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ea9b579d534736aa219bae09bb71fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":290},
                "size":{
                  "width":230,
                  "height":510},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u10.png"}},
{
          "id":"58a8c6350df4484fb02d785777ea5728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":290},
            "size":{
              "width":240,
              "height":510},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bf71063fc324392a477435867879807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":290},
                "size":{
                  "width":240,
                  "height":510},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u14.png"}},
{
          "id":"49b8bc7f0e9945b092467728d7bd727b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":300},
            "size":{
              "width":182,
              "height":491}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c27c9b908de946c6b33d4809ee5c6dca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":300},
                "size":{
                  "width":182,
                  "height":491}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u16.png"}},
{
          "id":"3636eacd74604ef19338236b6e678ec1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":300},
            "size":{
              "width":173,
              "height":493}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb89b09c6ea646d4a277636fd0d5ab79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":300},
                "size":{
                  "width":173,
                  "height":493}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u18.png"}},
{
          "id":"e2b8c676778f4d5595551c9d81eadcbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":300},
            "size":{
              "width":176,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"397e270894ee46d981f6b6c0a9e843b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":300},
                "size":{
                  "width":176,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u20.png"}},
{
          "id":"4e261770f514447eb80f16607080ed1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":74},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca16008cb9db4f8ab1ee525a583fee94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":74},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3ec7acee133442bae89f88181fe16ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":771,
              "y":74},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd11f67cb26d4bc8808f94bde663078e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":771,
                  "y":74},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20cd12dad84649c3846b8f0bcc15ff32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":893,
              "y":74},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d1973aa07444f7ae871d7749efc3b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":893,
                  "y":74},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"871b003297fb4062af15bf458121a8ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":50,
              "y":90},
            "size":{
              "width":880,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3b4cefe8ad4b4f881c7ae464d75c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":50,
                  "y":90},
                "size":{
                  "width":880,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u28.png"}},
{
          "id":"74600fa6f3b847cab833dbe00560b42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":347,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb9716829144adebff91a2de8998568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":347,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-成功登录",
                      "target":{
                        "targetType":"page",
                        "url":"主页-成功登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"153ac1fb57cd4225872f691e9734b5eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":467,
              "y":102},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a5b9cc1b10d49c186210aaedd5b61d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":467,
                  "y":102},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf36968991d2466dacc6d64e46c07564",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":102},
            "size":{
              "width":10,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页-直播大厅/u19_line.png"}},
{
          "id":"326099a367614ec094ff1d957dc4310a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0x56F2F2F2},
            "location":{
              "x":150,
              "y":102},
            "size":{
              "width":170,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1738809f16164c6786194a8f60c122d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0x56F2F2F2},
                "location":{
                  "x":150,
                  "y":102},
                "size":{
                  "width":170,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u20.png"}},
{
          "id":"b1c01d502bbf474783b74748044a5a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":300},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b90177625e470792428f6197bbea83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":300},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u37.png"}},
{
          "id":"65719ce2e17f4d449e60a6fbf081d100",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":300},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f0061e3cd942208a7babf75d458bbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":300},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u37.png"}},
{
          "id":"13d348b97cb64b4c866555954758e6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":300},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab544fda031b4ba29d51413004202382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":300},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排行榜/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6b05d11e03d141398af0aa81aab8753d":{
      "scriptId":"u0"},
    "fea58760b33e47d097fef70c8df7ac7a":{
      "scriptId":"u1"},
    "3a580949755242c38e7d2c052162cf8e":{
      "scriptId":"u2"},
    "e97f5dfaa3c04bd9aa571b8682e0cf63":{
      "scriptId":"u3"},
    "23a8b2634ac94bc3b0e12b7bbec8a4ec":{
      "scriptId":"u4"},
    "88b29b0449d243f8958601962e7af590":{
      "scriptId":"u5"},
    "797c28d2b0f04867a0adc20eb69f9001":{
      "scriptId":"u6"},
    "aa63076c043a4c608415bfbcfe7541e7":{
      "scriptId":"u7"},
    "2dd054dac489469490013a8e5f6172cf":{
      "scriptId":"u8"},
    "7b1baf0ea68949acbef3d006167160f7":{
      "scriptId":"u9"},
    "97b79dced86049228ec44b36c1b0e830":{
      "scriptId":"u10"},
    "38aa2ed4ea8043dca43e85b20330e0a7":{
      "scriptId":"u11"},
    "1c53a089eeb54d8d8aa1f8956cf2ce06":{
      "scriptId":"u12"},
    "49ea9b579d534736aa219bae09bb71fc":{
      "scriptId":"u13"},
    "58a8c6350df4484fb02d785777ea5728":{
      "scriptId":"u14"},
    "2bf71063fc324392a477435867879807":{
      "scriptId":"u15"},
    "49b8bc7f0e9945b092467728d7bd727b":{
      "scriptId":"u16"},
    "c27c9b908de946c6b33d4809ee5c6dca":{
      "scriptId":"u17"},
    "3636eacd74604ef19338236b6e678ec1":{
      "scriptId":"u18"},
    "cb89b09c6ea646d4a277636fd0d5ab79":{
      "scriptId":"u19"},
    "e2b8c676778f4d5595551c9d81eadcbe":{
      "scriptId":"u20"},
    "397e270894ee46d981f6b6c0a9e843b8":{
      "scriptId":"u21"},
    "4e261770f514447eb80f16607080ed1a":{
      "scriptId":"u22"},
    "ca16008cb9db4f8ab1ee525a583fee94":{
      "scriptId":"u23"},
    "a3ec7acee133442bae89f88181fe16ca":{
      "scriptId":"u24"},
    "dd11f67cb26d4bc8808f94bde663078e":{
      "scriptId":"u25"},
    "20cd12dad84649c3846b8f0bcc15ff32":{
      "scriptId":"u26"},
    "d4d1973aa07444f7ae871d7749efc3b4":{
      "scriptId":"u27"},
    "871b003297fb4062af15bf458121a8ad":{
      "scriptId":"u28"},
    "3e3b4cefe8ad4b4f881c7ae464d75c7c":{
      "scriptId":"u29"},
    "74600fa6f3b847cab833dbe00560b42b":{
      "scriptId":"u30"},
    "9fb9716829144adebff91a2de8998568":{
      "scriptId":"u31"},
    "153ac1fb57cd4225872f691e9734b5eb":{
      "scriptId":"u32"},
    "3a5b9cc1b10d49c186210aaedd5b61d6":{
      "scriptId":"u33"},
    "cf36968991d2466dacc6d64e46c07564":{
      "scriptId":"u34"},
    "326099a367614ec094ff1d957dc4310a":{
      "scriptId":"u35"},
    "1738809f16164c6786194a8f60c122d6":{
      "scriptId":"u36"},
    "b1c01d502bbf474783b74748044a5a4e":{
      "scriptId":"u37"},
    "58b90177625e470792428f6197bbea83":{
      "scriptId":"u38"},
    "65719ce2e17f4d449e60a6fbf081d100":{
      "scriptId":"u39"},
    "20f0061e3cd942208a7babf75d458bbd":{
      "scriptId":"u40"},
    "13d348b97cb64b4c866555954758e6ff":{
      "scriptId":"u41"},
    "ab544fda031b4ba29d51413004202382":{
      "scriptId":"u42"}}});