$axure.loadCurrentPage({
  "url":"主播直播间.html",
  "generationDate":new Date(1385387514031.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ff03006e11a4492d96f53e0a7e045722",
    "type":"Axure:Page",
    "name":"主播直播间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"827f487b8d6b4200adc2f6c297ad0eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":1020,
              "height":910}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda56102b75f4e16b528fef939ca2501",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":40},
                "size":{
                  "width":1020,
                  "height":910}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u0.png"}},
{
          "id":"a556654285524f5b84394e95a96d8e4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":107},
            "size":{
              "width":830,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98cf8b2e386d41a19dcc1b677579dd51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":107},
                "size":{
                  "width":830,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u2.png"}},
{
          "id":"ab4bf3322ebe490bacfc12382595e73e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":117},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-直播大厅",
                      "target":{
                        "targetType":"page",
                        "url":"主页-直播大厅.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"438c4e86981040e4be2a0bf4822b428e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":91},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3867b85fc2f4c79b92c7c0fe21c1157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":91},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e20c7a8a8d5641b2b392cf513bcbb8da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":91},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e91ff3639584de29b1c77b411707c45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":91},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f397a7020d6e4c598c488d71e8bc8965",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":923,
              "y":91},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3d3adaa18946aeb1ad1c83c69619f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":923,
                  "y":91},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5731fffe44bf4cb29862c2ee65e44058",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":129},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5306155178fb423db80d7dc95f489092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":129},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a203838e178a46b3bc56b40d0427a4b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":170},
            "size":{
              "width":830,
              "height":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ebbfe991284d76bc79de44a92770b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":170},
                "size":{
                  "width":830,
                  "height":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u13.png"}},
{
          "id":"265b6b56c55e4964870057d82563c854",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":230},
            "size":{
              "width":240,
              "height":330},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c285ce5dc842d78f68facebe240965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":230},
                "size":{
                  "width":240,
                  "height":330},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u15.png"}},
{
          "id":"997531d71e6b420b8d66b0a8fe5a533d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":230},
            "size":{
              "width":87,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d19cd91541c450fa02f8bbba89d156b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":230},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u17.png"}},
{
          "id":"0be158e4136c45d8af23ae4e12eaa473",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":230},
            "size":{
              "width":139,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f4478594084bf9a5e357673c4cb5ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":230},
                "size":{
                  "width":139,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u19.png"}},
{
          "id":"0b84b40d3cbc4a53b5f36d1d0b5eff76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":230},
            "size":{
              "width":79,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18779aa7026548f8bf944f1dcc81db0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":230},
                "size":{
                  "width":79,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u21.png"}},
{
          "id":"3f57defb6a7b4663baf73274e18905fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":274},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b55deb1ab19847269583d2d19600316a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":274},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63f5b23ef4d2438098831603e1d8825a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":304},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d885aba6ff64a0c96c21017f66aeefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":304},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f47aff867de44961855e89712317fbc9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":570},
            "size":{
              "width":67,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bb0f987a2538447ea4686dcee5bfb4da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":570},
            "size":{
              "width":230,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70adbc3f6f5c45eb9404b5fd2280929e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":570},
                "size":{
                  "width":230,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u28.png"}},
{
          "id":"e727a4d25469435e9fe3755bdb85aebf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":570},
            "size":{
              "width":46,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9e19cc139904baca6ec77d2d51e92ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":570},
                "size":{
                  "width":46,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u30.png"}},
{
          "id":"49e92348e1f643baadb58ae3e7bf90b6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":570},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a3d834a2abb84366a843ec2c804fd6f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":570},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dba62d87fe14f519fb870062ba47fd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":570},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u33.png"}},
{
          "id":"3d4d8b2bde244c55bfb3bf328f66c654",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":572},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd568384a57443a7867b650fb3ac8f33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":572},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b30c0a9a8b1419f95efb5c6d680b319",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":572},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0252f50f425d4d60a653a447ea354412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":572},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7627bf5d4533436d9221542fc5175b7b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":570},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0b310aa67ea64f349118d48830b2ea1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":576},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f953c0233142b598c71cc2ceea39ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":576},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f705acd8a744457d9fa5cc29f492d1f2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":567},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2a5e6a81d9834d7fa6838a09351ccfe6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":572},
            "size":{
              "width":63,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"346807aaebc7440fa2aa9c9a09dc3024",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":214},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e469d863a849c3b1bb931f98deaa52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":214},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef0817af46d04ccd889102395efaded7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e59bf1d2fdd8487f90e7402c229bb0a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"257c43cae5bb4ea886549d43e0fc8323",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":850},
            "size":{
              "width":1020,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ef29920f5c94f4597bce365ecfb231e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":850},
                "size":{
                  "width":1020,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u48.png"}},
{
          "id":"f0ebe1e55ec545239e44c41669423f16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":911},
            "size":{
              "width":470,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff2ea8550fa4467a8a985cab96f19128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":382,
                  "y":911},
                "size":{
                  "width":470,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u256.png"}},
{
          "id":"fd5fa52b2d9f4ddd929d6192a88beeeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF515151},
            "location":{
              "x":160,
              "y":230},
            "size":{
              "width":340,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0489774e2894f3baed06075011f3993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151},
                "location":{
                  "x":160,
                  "y":230},
                "size":{
                  "width":340,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u52.png"}},
{
          "id":"2e751970be5c478185c32f4c2abcfa23",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":567},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cff668cab9584bfc98a1de086bde2b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":274},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d73ed1b55194b0bb9592b18d61398a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":274},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e930d1b184a64938925d4990483f6edb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":304},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de3db439a6984d0fa33949bde95144f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":304},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5d15764d8945bab78fdeef101edb5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":338},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b46bf6bcb3498a83df56e656f01afe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":338},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"280b6e9bfa324c369bd47f733e7668ed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":205},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"831a2800d4d64b5b89e0f850bd19017f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":610},
            "size":{
              "width":760,
              "height":100},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f722096a46458e9753fde4ac1be798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":610},
                "size":{
                  "width":760,
                  "height":100},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始直播/u65.png"}},
{
          "id":"a96000baa92340248043f9a9ae2c3ca9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86e05ada3eb9402e8537adf7cf149561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bccfe1148694607867599e3d29c0aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8c4c8df536449d488b5ac8d6303838d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28d6c5a66ea1499fae7ec1808288314e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":230},
            "size":{
              "width":340,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4408c7a1d3c4445da3994c2e3d9f9044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":230},
                "size":{
                  "width":340,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主播直播间/u68.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "827f487b8d6b4200adc2f6c297ad0eb3":{
      "scriptId":"u0"},
    "eda56102b75f4e16b528fef939ca2501":{
      "scriptId":"u1"},
    "a556654285524f5b84394e95a96d8e4e":{
      "scriptId":"u2"},
    "98cf8b2e386d41a19dcc1b677579dd51":{
      "scriptId":"u3"},
    "ab4bf3322ebe490bacfc12382595e73e":{
      "scriptId":"u4"},
    "438c4e86981040e4be2a0bf4822b428e":{
      "scriptId":"u5"},
    "b3867b85fc2f4c79b92c7c0fe21c1157":{
      "scriptId":"u6"},
    "e20c7a8a8d5641b2b392cf513bcbb8da":{
      "scriptId":"u7"},
    "1e91ff3639584de29b1c77b411707c45":{
      "scriptId":"u8"},
    "f397a7020d6e4c598c488d71e8bc8965":{
      "scriptId":"u9"},
    "5a3d3adaa18946aeb1ad1c83c69619f3":{
      "scriptId":"u10"},
    "5731fffe44bf4cb29862c2ee65e44058":{
      "scriptId":"u11"},
    "5306155178fb423db80d7dc95f489092":{
      "scriptId":"u12"},
    "a203838e178a46b3bc56b40d0427a4b1":{
      "scriptId":"u13"},
    "43ebbfe991284d76bc79de44a92770b0":{
      "scriptId":"u14"},
    "265b6b56c55e4964870057d82563c854":{
      "scriptId":"u15"},
    "85c285ce5dc842d78f68facebe240965":{
      "scriptId":"u16"},
    "997531d71e6b420b8d66b0a8fe5a533d":{
      "scriptId":"u17"},
    "5d19cd91541c450fa02f8bbba89d156b":{
      "scriptId":"u18"},
    "0be158e4136c45d8af23ae4e12eaa473":{
      "scriptId":"u19"},
    "44f4478594084bf9a5e357673c4cb5ef":{
      "scriptId":"u20"},
    "0b84b40d3cbc4a53b5f36d1d0b5eff76":{
      "scriptId":"u21"},
    "18779aa7026548f8bf944f1dcc81db0c":{
      "scriptId":"u22"},
    "3f57defb6a7b4663baf73274e18905fa":{
      "scriptId":"u23"},
    "b55deb1ab19847269583d2d19600316a":{
      "scriptId":"u24"},
    "63f5b23ef4d2438098831603e1d8825a":{
      "scriptId":"u25"},
    "6d885aba6ff64a0c96c21017f66aeefb":{
      "scriptId":"u26"},
    "f47aff867de44961855e89712317fbc9":{
      "scriptId":"u27"},
    "bb0f987a2538447ea4686dcee5bfb4da":{
      "scriptId":"u28"},
    "70adbc3f6f5c45eb9404b5fd2280929e":{
      "scriptId":"u29"},
    "e727a4d25469435e9fe3755bdb85aebf":{
      "scriptId":"u30"},
    "e9e19cc139904baca6ec77d2d51e92ec":{
      "scriptId":"u31"},
    "49e92348e1f643baadb58ae3e7bf90b6":{
      "scriptId":"u32"},
    "a3d834a2abb84366a843ec2c804fd6f3":{
      "scriptId":"u33"},
    "5dba62d87fe14f519fb870062ba47fd6":{
      "scriptId":"u34"},
    "3d4d8b2bde244c55bfb3bf328f66c654":{
      "scriptId":"u35"},
    "cd568384a57443a7867b650fb3ac8f33":{
      "scriptId":"u36"},
    "5b30c0a9a8b1419f95efb5c6d680b319":{
      "scriptId":"u37"},
    "0252f50f425d4d60a653a447ea354412":{
      "scriptId":"u38"},
    "7627bf5d4533436d9221542fc5175b7b":{
      "scriptId":"u39"},
    "0b310aa67ea64f349118d48830b2ea1d":{
      "scriptId":"u40"},
    "24f953c0233142b598c71cc2ceea39ea":{
      "scriptId":"u41"},
    "f705acd8a744457d9fa5cc29f492d1f2":{
      "scriptId":"u42"},
    "2a5e6a81d9834d7fa6838a09351ccfe6":{
      "scriptId":"u43"},
    "346807aaebc7440fa2aa9c9a09dc3024":{
      "scriptId":"u44"},
    "a4e469d863a849c3b1bb931f98deaa52":{
      "scriptId":"u45"},
    "ef0817af46d04ccd889102395efaded7":{
      "scriptId":"u46"},
    "e59bf1d2fdd8487f90e7402c229bb0a9":{
      "scriptId":"u47"},
    "257c43cae5bb4ea886549d43e0fc8323":{
      "scriptId":"u48"},
    "6ef29920f5c94f4597bce365ecfb231e":{
      "scriptId":"u49"},
    "f0ebe1e55ec545239e44c41669423f16":{
      "scriptId":"u50"},
    "ff2ea8550fa4467a8a985cab96f19128":{
      "scriptId":"u51"},
    "fd5fa52b2d9f4ddd929d6192a88beeeb":{
      "scriptId":"u52"},
    "b0489774e2894f3baed06075011f3993":{
      "scriptId":"u53"},
    "2e751970be5c478185c32f4c2abcfa23":{
      "scriptId":"u54"},
    "cff668cab9584bfc98a1de086bde2b2c":{
      "scriptId":"u55"},
    "2d73ed1b55194b0bb9592b18d61398a8":{
      "scriptId":"u56"},
    "e930d1b184a64938925d4990483f6edb":{
      "scriptId":"u57"},
    "de3db439a6984d0fa33949bde95144f0":{
      "scriptId":"u58"},
    "0c5d15764d8945bab78fdeef101edb5c":{
      "scriptId":"u59"},
    "51b46bf6bcb3498a83df56e656f01afe":{
      "scriptId":"u60"},
    "280b6e9bfa324c369bd47f733e7668ed":{
      "scriptId":"u61"},
    "831a2800d4d64b5b89e0f850bd19017f":{
      "scriptId":"u62"},
    "47f722096a46458e9753fde4ac1be798":{
      "scriptId":"u63"},
    "a96000baa92340248043f9a9ae2c3ca9":{
      "scriptId":"u64"},
    "86e05ada3eb9402e8537adf7cf149561":{
      "scriptId":"u65"},
    "8bccfe1148694607867599e3d29c0aa6":{
      "scriptId":"u66"},
    "a8c4c8df536449d488b5ac8d6303838d":{
      "scriptId":"u67"},
    "28d6c5a66ea1499fae7ec1808288314e":{
      "scriptId":"u68"},
    "4408c7a1d3c4445da3994c2e3d9f9044":{
      "scriptId":"u69"}}});