$axure.loadCurrentPage({
  "url":"商城道具.html",
  "generationDate":new Date(1385387516406.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"67a0fb0a0e1b4404a0ae4a8213d6188d",
    "type":"Axure:Page",
    "name":"商城道具",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11cf2914074a4693b9b4a6e69bf318a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":1010,
              "height":720}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d2e1e8ab9524bc4b535dd65f12e7f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":1010,
                  "height":720}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u0.png"}},
{
          "id":"3544bd9e72414ab7ba64658074547ba1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":151},
            "size":{
              "width":810,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c930b40d29c54e94a066e8822c67412e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":151},
                "size":{
                  "width":810,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u2.png"}},
{
          "id":"63da09b04cd549219f8062b91adf31d6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":10,
              "height":16}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商城vip/u4_line.png"}},
{
          "id":"0a6a577d883e4cd3aa2a1906d6b2320e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":164},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4735f172e4744693b3c4c7ed0cd48f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":163,
                  "y":164},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95e570bf1a6649dfac5bd309df7df127",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e3523e65574d0683e4b50c8bdea725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":215,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82089ab55da94b979530cc865383bcfe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":220},
            "size":{
              "width":810,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商城道具/u9_line.png"}},
{
          "id":"e9a2224f940b40ea93eb51b25db02b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":204},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a5ffc31034c423095a831440aeea669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":204},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bba430d4d7a04555ae88b6623b6a6627",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":270},
            "size":{
              "width":115,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c7d76af08864223b37c5171cc4a2a6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":270},
                "size":{
                  "width":115,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u12.png"}},
{
          "id":"89e2172a5f3544cfa32ff425255ec567",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819.5,
              "y":480},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e516cef19f4ad395a3be7ec86dccd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819.5,
                  "y":480},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"b525da3381a1439994552a7c0123fc7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":480},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5954bcb4d0e34a809b8f59f51c5d87da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":480},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"031f0484d03540b7a9ace7100f08eda9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":480},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a1071fa4ce4661a6d8875265a2bc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":480},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"949a38aed8564142a5f311731135ca6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":270},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3177016d0b740c3989b592053ee55bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":270},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"ea227b58162143278408fc55d7011572",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":480},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b002b56e10c443b1902c4ee950f5cb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":480},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"943bbd0cb8534432ba779b8cbfe8ed5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":270},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3dfbe15cc77462fa281c8e525e8a0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":270},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"5e565e34743e4900861cfef7cd76071f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":270},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1bf5885bf6f40099e795cc73cdb1061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":270},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城道具/u14.png"}},
{
          "id":"2b583ee6e5c4429f8da49f952f871d87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":404},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347fe38b11ea4025891b0ae7d388c809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":404},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f21161e5a1142b7bf249cd70fa0c301",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":172.5,
              "y":430},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4c7a5961ba114477a0327c74684b021f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":404},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239e87e269ae4046a70d64b5f4660857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":404},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a7c6dd88f9048d6abc32da389da60ff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":430},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0bf0d4ade6f14cb590ba17b08e416628",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":404},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee5d551880854ce3b4c82e29c9c351be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":404},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40c1ad731cd7411389f610ce0d332a6f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":430},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"04c805251a324da6a5efb8261ee48b4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":829,
              "y":404},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ca877a31a84082878fd7f5879c75e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":829,
                  "y":404},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e43c504bb1147e997ee52bd68346084",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":847,
              "y":430},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"241557006f414c898c45aea514d19d02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":640},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6cc273c95c042d08f3e91ff5aac301d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":640},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9559945c5d574e0aa2cd171b0a717234",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":171.5,
              "y":666},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a88b6e488a394398b88381b3bc218342",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":640},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"303534bd1a644875bd104442a5040b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":640},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57c90c6440cb47e59c056f20d891b5d3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":666},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c071f45b53444ebdaf96215a6b142808",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":640},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70bfec2ba5ae409084f152a9da48f0d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":629,
                  "y":640},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3de9bbc53d094094bdea7508a0c9c32d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":666},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4247d1bdc87c4b3196ebe7481317fdff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":829,
              "y":640},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a90b414118ea4be0bae893ed8b532231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":829,
                  "y":640},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56f8ca0403474501951f998f1d566223",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":847,
              "y":666},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"83903a0e3305424db5adc3ab88d03300",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":829,
              "y":41},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fe43bb7462c4e85838779c70f6c831f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":829,
                  "y":41},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17f2743d03164df4b6d8e6aace15bfed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":41},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a68b16896a24f41a97affe3f563e5e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":41},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17ebee41dde54c828b44fef1106e561a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1012,
              "y":41},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4341fce2281244a2b76e72d5e0ee9cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1012,
                  "y":41},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值支付宝",
                      "target":{
                        "targetType":"page",
                        "url":"充值支付宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b63f93598aa141e5929eeab17748765d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":40,
              "y":57},
            "size":{
              "width":1010,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f4c02fd1c1a48929c7cbc2cdaecb527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":40,
                  "y":57},
                "size":{
                  "width":1010,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城vip/u47.png"}},
{
          "id":"39bcf573305a451db5287fad4f6ce0de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":337,
              "y":69},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d14f4441051c4138bb3c49ef03de25ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":337,
                  "y":69},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页-成功登录",
                      "target":{
                        "targetType":"page",
                        "url":"主页-成功登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce50be6784bc4bfb9879436ede21405c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":69},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e7b1821c4b94ce48a0a743603b21d9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":69},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商城VIP",
                      "target":{
                        "targetType":"page",
                        "url":"商城vip.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"182ebdb1a8674af28e089f9a825611d9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":69},
            "size":{
              "width":10,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页-直播大厅/u19_line.png"}},
{
          "id":"e329bbc663bb46ee92e3693195ddabdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0x56F2F2F2},
            "location":{
              "x":140,
              "y":69},
            "size":{
              "width":170,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ae12113ff2479b928d970ebabb0681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0x56F2F2F2},
                "location":{
                  "x":140,
                  "y":69},
                "size":{
                  "width":170,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u20.png"}},
{
          "id":"e0cd50800f184040bbcb4ba6f9607301",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":976,
              "y":69},
            "size":{
              "width":294,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e749a6cbf684c32a29fafc910bb234d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":976,
                  "y":69},
                "size":{
                  "width":294,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页-直播大厅/u283.png"}},
{
          "id":"1966652fb5c34ee58575e2f7533c610b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1220,
              "y":41},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0715863c050646019d1bf1751cb686bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1220,
                  "y":41},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "11cf2914074a4693b9b4a6e69bf318a3":{
      "scriptId":"u0"},
    "7d2e1e8ab9524bc4b535dd65f12e7f5e":{
      "scriptId":"u1"},
    "3544bd9e72414ab7ba64658074547ba1":{
      "scriptId":"u2"},
    "c930b40d29c54e94a066e8822c67412e":{
      "scriptId":"u3"},
    "63da09b04cd549219f8062b91adf31d6":{
      "scriptId":"u4"},
    "0a6a577d883e4cd3aa2a1906d6b2320e":{
      "scriptId":"u5"},
    "4735f172e4744693b3c4c7ed0cd48f45":{
      "scriptId":"u6"},
    "95e570bf1a6649dfac5bd309df7df127":{
      "scriptId":"u7"},
    "71e3523e65574d0683e4b50c8bdea725":{
      "scriptId":"u8"},
    "82089ab55da94b979530cc865383bcfe":{
      "scriptId":"u9"},
    "e9a2224f940b40ea93eb51b25db02b6c":{
      "scriptId":"u10"},
    "0a5ffc31034c423095a831440aeea669":{
      "scriptId":"u11"},
    "bba430d4d7a04555ae88b6623b6a6627":{
      "scriptId":"u12"},
    "3c7d76af08864223b37c5171cc4a2a6d":{
      "scriptId":"u13"},
    "89e2172a5f3544cfa32ff425255ec567":{
      "scriptId":"u14"},
    "65e516cef19f4ad395a3be7ec86dccd6":{
      "scriptId":"u15"},
    "b525da3381a1439994552a7c0123fc7d":{
      "scriptId":"u16"},
    "5954bcb4d0e34a809b8f59f51c5d87da":{
      "scriptId":"u17"},
    "031f0484d03540b7a9ace7100f08eda9":{
      "scriptId":"u18"},
    "90a1071fa4ce4661a6d8875265a2bc2a":{
      "scriptId":"u19"},
    "949a38aed8564142a5f311731135ca6d":{
      "scriptId":"u20"},
    "c3177016d0b740c3989b592053ee55bd":{
      "scriptId":"u21"},
    "ea227b58162143278408fc55d7011572":{
      "scriptId":"u22"},
    "b002b56e10c443b1902c4ee950f5cb60":{
      "scriptId":"u23"},
    "943bbd0cb8534432ba779b8cbfe8ed5d":{
      "scriptId":"u24"},
    "d3dfbe15cc77462fa281c8e525e8a0db":{
      "scriptId":"u25"},
    "5e565e34743e4900861cfef7cd76071f":{
      "scriptId":"u26"},
    "f1bf5885bf6f40099e795cc73cdb1061":{
      "scriptId":"u27"},
    "2b583ee6e5c4429f8da49f952f871d87":{
      "scriptId":"u28"},
    "347fe38b11ea4025891b0ae7d388c809":{
      "scriptId":"u29"},
    "2f21161e5a1142b7bf249cd70fa0c301":{
      "scriptId":"u30"},
    "4c7a5961ba114477a0327c74684b021f":{
      "scriptId":"u31"},
    "239e87e269ae4046a70d64b5f4660857":{
      "scriptId":"u32"},
    "6a7c6dd88f9048d6abc32da389da60ff":{
      "scriptId":"u33"},
    "0bf0d4ade6f14cb590ba17b08e416628":{
      "scriptId":"u34"},
    "ee5d551880854ce3b4c82e29c9c351be":{
      "scriptId":"u35"},
    "40c1ad731cd7411389f610ce0d332a6f":{
      "scriptId":"u36"},
    "04c805251a324da6a5efb8261ee48b4e":{
      "scriptId":"u37"},
    "33ca877a31a84082878fd7f5879c75e8":{
      "scriptId":"u38"},
    "2e43c504bb1147e997ee52bd68346084":{
      "scriptId":"u39"},
    "241557006f414c898c45aea514d19d02":{
      "scriptId":"u40"},
    "f6cc273c95c042d08f3e91ff5aac301d":{
      "scriptId":"u41"},
    "9559945c5d574e0aa2cd171b0a717234":{
      "scriptId":"u42"},
    "a88b6e488a394398b88381b3bc218342":{
      "scriptId":"u43"},
    "303534bd1a644875bd104442a5040b86":{
      "scriptId":"u44"},
    "57c90c6440cb47e59c056f20d891b5d3":{
      "scriptId":"u45"},
    "c071f45b53444ebdaf96215a6b142808":{
      "scriptId":"u46"},
    "70bfec2ba5ae409084f152a9da48f0d0":{
      "scriptId":"u47"},
    "3de9bbc53d094094bdea7508a0c9c32d":{
      "scriptId":"u48"},
    "4247d1bdc87c4b3196ebe7481317fdff":{
      "scriptId":"u49"},
    "a90b414118ea4be0bae893ed8b532231":{
      "scriptId":"u50"},
    "56f8ca0403474501951f998f1d566223":{
      "scriptId":"u51"},
    "83903a0e3305424db5adc3ab88d03300":{
      "scriptId":"u52"},
    "8fe43bb7462c4e85838779c70f6c831f":{
      "scriptId":"u53"},
    "17f2743d03164df4b6d8e6aace15bfed":{
      "scriptId":"u54"},
    "5a68b16896a24f41a97affe3f563e5e9":{
      "scriptId":"u55"},
    "17ebee41dde54c828b44fef1106e561a":{
      "scriptId":"u56"},
    "4341fce2281244a2b76e72d5e0ee9cc0":{
      "scriptId":"u57"},
    "b63f93598aa141e5929eeab17748765d":{
      "scriptId":"u58"},
    "7f4c02fd1c1a48929c7cbc2cdaecb527":{
      "scriptId":"u59"},
    "39bcf573305a451db5287fad4f6ce0de":{
      "scriptId":"u60"},
    "d14f4441051c4138bb3c49ef03de25ed":{
      "scriptId":"u61"},
    "ce50be6784bc4bfb9879436ede21405c":{
      "scriptId":"u62"},
    "0e7b1821c4b94ce48a0a743603b21d9e":{
      "scriptId":"u63"},
    "182ebdb1a8674af28e089f9a825611d9":{
      "scriptId":"u64"},
    "e329bbc663bb46ee92e3693195ddabdc":{
      "scriptId":"u65"},
    "b0ae12113ff2479b928d970ebabb0681":{
      "scriptId":"u66"},
    "e0cd50800f184040bbcb4ba6f9607301":{
      "scriptId":"u67"},
    "5e749a6cbf684c32a29fafc910bb234d":{
      "scriptId":"u68"},
    "1966652fb5c34ee58575e2f7533c610b":{
      "scriptId":"u69"},
    "0715863c050646019d1bf1751cb686bf":{
      "scriptId":"u70"}}});